/**
 * Custom MDI SVG icon set for Vuetify.
 *
 * Replaces @mdi/font with tree-shakeable @mdi/js imports.
 * Template code keeps using `mdi-xxx` strings — this set resolves them
 * to SVG paths at render time.
 */
import { h } from 'vue'
import type { IconSet, IconProps } from 'vuetify'

// ── App icons (used in templates) ──────────────────────────────────
import {
  mdiAccount,
  mdiAccountGroup,
  mdiAlert,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowUp,
  mdiArrowUpCircleOutline,
  mdiBellOutline,
  mdiBrain,
  mdiCached,
  mdiCalendarToday,
  mdiChartLine,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCheckDecagram,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircleMedium,
  mdiCircleOutline,
  mdiClipboardTextOutline,
  mdiClockEditOutline,
  mdiClockPlusOutline,
  mdiClose,
  mdiCodeBraces,
  mdiCodeTags,
  mdiCogOutline,
  mdiCommentTextOutline,
  mdiConsole,
  mdiCounter,
  mdiCurrencyUsd,
  mdiDelete,
  mdiDownload,
  mdiDrag,
  mdiFileDocumentOutline,
  mdiFileMultipleOutline,
  mdiFileOutline,
  mdiFileRefreshOutline,
  mdiFileTree,
  mdiFolder,
  mdiFolderOpen,
  mdiFolderOutline,
  mdiFormatListChecks,
  mdiHelpCircleOutline,
  mdiInformation,
  mdiInformationOutline,
  mdiLayersOutline,
  mdiLightningBolt,
  mdiMagnify,
  mdiMinusCircleOutline,
  mdiPencil,
  mdiPercent,
  mdiPlay,
  mdiPlayCircleOutline,
  mdiPlus,
  mdiProgressClock,
  mdiRefresh,
  mdiSend,
  mdiShieldCheck,
  mdiShieldLockOutline,
  mdiSortCalendarDescending,
  mdiSourceCommit,
  mdiStopCircle,
  mdiTestTube,
  mdiTools,
  mdiTranslate,
  mdiUpdate,
  mdiViewList,
  mdiWhiteBalanceSunny,
} from '@mdi/js'

// ── Vuetify internal icons (used by components like VCheckbox, VSelect…) ──
import {
  mdiCalendar,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiCircle,
  mdiCloseCircle,
  mdiEyedropper,
  mdiMenu,
  mdiMenuDown,
  mdiMinus,
  mdiMinusBox,
  mdiPageFirst,
  mdiPageLast,
  mdiPaperclip,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiStar,
  mdiStarHalfFull,
  mdiStarOutline,
  mdiUnfoldMoreHorizontal,
} from '@mdi/js'

// ── Name → SVG path map (kebab-case, no "mdi-" prefix) ────────────
const iconPaths: Record<string, string> = {
  account: mdiAccount,
  'account-group': mdiAccountGroup,
  alert: mdiAlert,
  'alert-circle-outline': mdiAlertCircleOutline,
  'alert-outline': mdiAlertOutline,
  'arrow-down': mdiArrowDown,
  'arrow-left': mdiArrowLeft,
  'arrow-up': mdiArrowUp,
  'arrow-up-circle-outline': mdiArrowUpCircleOutline,
  'bell-outline': mdiBellOutline,
  brain: mdiBrain,
  cached: mdiCached,
  calendar: mdiCalendar,
  'calendar-today': mdiCalendarToday,
  'chart-line': mdiChartLine,
  check: mdiCheck,
  'check-circle': mdiCheckCircle,
  'check-circle-outline': mdiCheckCircleOutline,
  'check-decagram': mdiCheckDecagram,
  'checkbox-blank-outline': mdiCheckboxBlankOutline,
  'checkbox-marked': mdiCheckboxMarked,
  'chevron-down': mdiChevronDown,
  'chevron-left': mdiChevronLeft,
  'chevron-right': mdiChevronRight,
  'chevron-up': mdiChevronUp,
  circle: mdiCircle,
  'circle-medium': mdiCircleMedium,
  'circle-outline': mdiCircleOutline,
  'clipboard-text-outline': mdiClipboardTextOutline,
  'clock-edit-outline': mdiClockEditOutline,
  'clock-plus-outline': mdiClockPlusOutline,
  close: mdiClose,
  'close-circle': mdiCloseCircle,
  'code-braces': mdiCodeBraces,
  'code-tags': mdiCodeTags,
  'cog-outline': mdiCogOutline,
  'comment-text-outline': mdiCommentTextOutline,
  console: mdiConsole,
  counter: mdiCounter,
  'currency-usd': mdiCurrencyUsd,
  delete: mdiDelete,
  download: mdiDownload,
  drag: mdiDrag,
  eyedropper: mdiEyedropper,
  'file-document-outline': mdiFileDocumentOutline,
  'file-multiple-outline': mdiFileMultipleOutline,
  'file-outline': mdiFileOutline,
  'file-refresh-outline': mdiFileRefreshOutline,
  'file-tree': mdiFileTree,
  folder: mdiFolder,
  'folder-open': mdiFolderOpen,
  'folder-outline': mdiFolderOutline,
  'format-list-checks': mdiFormatListChecks,
  'help-circle-outline': mdiHelpCircleOutline,
  information: mdiInformation,
  'information-outline': mdiInformationOutline,
  'layers-outline': mdiLayersOutline,
  'lightning-bolt': mdiLightningBolt,
  magnify: mdiMagnify,
  menu: mdiMenu,
  'menu-down': mdiMenuDown,
  minus: mdiMinus,
  'minus-box': mdiMinusBox,
  'minus-circle-outline': mdiMinusCircleOutline,
  'page-first': mdiPageFirst,
  'page-last': mdiPageLast,
  paperclip: mdiPaperclip,
  pencil: mdiPencil,
  percent: mdiPercent,
  play: mdiPlay,
  'play-circle-outline': mdiPlayCircleOutline,
  plus: mdiPlus,
  'progress-clock': mdiProgressClock,
  'radiobox-blank': mdiRadioboxBlank,
  'radiobox-marked': mdiRadioboxMarked,
  refresh: mdiRefresh,
  send: mdiSend,
  'shield-check': mdiShieldCheck,
  'shield-lock-outline': mdiShieldLockOutline,
  'sort-calendar-descending': mdiSortCalendarDescending,
  'source-commit': mdiSourceCommit,
  star: mdiStar,
  'star-half-full': mdiStarHalfFull,
  'star-outline': mdiStarOutline,
  'stop-circle': mdiStopCircle,
  'test-tube': mdiTestTube,
  tools: mdiTools,
  translate: mdiTranslate,
  'unfold-more-horizontal': mdiUnfoldMoreHorizontal,
  update: mdiUpdate,
  'view-list': mdiViewList,
  'white-balance-sunny': mdiWhiteBalanceSunny,
}

// ── Vuetify internal aliases (used by VCheckbox, VSelect, VDialog…) ──
export const aliases: Record<string, string> = {
  collapse: mdiChevronUp,
  complete: mdiCheck,
  cancel: mdiCloseCircle,
  close: mdiClose,
  delete: mdiCloseCircle,
  clear: mdiClose,
  success: mdiCheckCircle,
  info: mdiInformation,
  warning: mdiAlert,
  error: mdiCloseCircle,
  prev: mdiChevronLeft,
  next: mdiChevronRight,
  checkboxOn: mdiCheckboxMarked,
  checkboxOff: mdiCheckboxBlankOutline,
  checkboxIndeterminate: mdiMinusBox,
  delimiter: mdiCircle,
  sortAsc: mdiArrowUp,
  sortDesc: mdiArrowDown,
  expand: mdiChevronDown,
  menu: mdiMenu,
  subgroup: mdiMenuDown,
  dropdown: mdiMenuDown,
  radioOn: mdiRadioboxMarked,
  radioOff: mdiRadioboxBlank,
  edit: mdiPencil,
  ratingEmpty: mdiStarOutline,
  ratingFull: mdiStar,
  ratingHalf: mdiStarHalfFull,
  loading: mdiCached,
  first: mdiPageFirst,
  last: mdiPageLast,
  unfold: mdiUnfoldMoreHorizontal,
  file: mdiPaperclip,
  plus: mdiPlus,
  minus: mdiMinus,
  calendar: mdiCalendar,
  eyeDropper: mdiEyedropper,
}

// ── Custom icon set: resolves names AND raw SVG paths ──────────────
export const mdiSvgSet: IconSet = {
  component: (props: IconProps) => {
    const icon = props.icon as string
    // Strip 'mdi-' prefix: Vuetify passes 'mdi-xxx' but iconPaths keys are 'xxx'
    const name = icon.startsWith('mdi-') ? icon.slice(4) : icon
    // Resolve name → SVG path, or use raw path if already an SVG path string
    const svgPath = iconPaths[name] ?? icon
    if (import.meta.env.DEV && !iconPaths[name] && icon.startsWith('mdi-')) {
      console.warn(`[mdiSvgSet] Missing icon: "${icon}" — add it to iconPaths in mdiSvgSet.ts`)
    }
    return h(props.tag, [
      h(
        'svg',
        {
          class: 'v-icon__svg',
          xmlns: 'http://www.w3.org/2000/svg',
          viewBox: '0 0 24 24',
          role: 'img',
          'aria-hidden': true,
        },
        [h('path', { d: svgPath })],
      ),
    ])
  },
}
