<script setup lang="ts">
/**
 * StreamView — POC affichage structuré de messages CLI stream-json (ADR-009 Option B).
 *
 * Remplace xterm.js pour les sessions agents Claude en affichant les blocs
 * de messages de façon structurée (texte, tool_use, tool_result, thinking, result).
 *
 * Câblé dans App.vue pour les tabs dont viewMode === 'stream' (T597).
 *
 * @module components/StreamView
 */
import { ref, computed, onMounted, onUnmounted, nextTick } from 'vue'
import { marked } from 'marked'
import hljs from 'highlight.js'
import DOMPurify from 'dompurify'
import { useTabsStore } from '@renderer/stores/tabs'
import { useTasksStore } from '@renderer/stores/tasks'
import { agentFg, agentBg, agentBorder, colorVersion } from '@renderer/utils/agentColor'

// highlight.js dark theme — scoped to .stream-markdown
import 'highlight.js/styles/github-dark.css'

// ── Markdown renderer (T678) ──────────────────────────────────────────────────

marked.use({
  renderer: {
    code({ text, lang }: { text: string; lang?: string }) {
      const language = lang && hljs.getLanguage(lang) ? lang : undefined
      const highlighted = language
        ? hljs.highlight(text, { language }).value
        : hljs.highlightAuto(text).value
      return `<pre class="hljs"><code class="${language ? `language-${language}` : ''}">${highlighted}</code></pre>`
    }
  }
})

/**
 * Renders Markdown text to sanitized HTML (T678).
 * DOMPurify prevents XSS — content arrives from network via Claude.
 */
function renderMarkdown(text: string): string {
  const raw = marked.parse(text) as string
  return DOMPurify.sanitize(raw)
}

// ── Types stream-json (ADR-009 §Types de messages JSONL) ─────────────────────

export interface StreamContentBlock {
  type: 'text' | 'tool_use' | 'tool_result' | 'thinking'
  /** text block */
  text?: string
  /** tool_use block */
  name?: string
  input?: Record<string, unknown>
  /** tool_result block */
  content?: string | Array<{ type: string; text?: string }>
  tool_use_id?: string
  is_error?: boolean
}

export interface StreamEvent {
  type: 'system' | 'user' | 'assistant' | 'result'
  subtype?: string
  session_id?: string
  message?: {
    role: string
    content: StreamContentBlock[]
  }
  cost_usd?: number
  num_turns?: number
  duration_ms?: number
}

// ── Props ────────────────────────────────────────────────────────────────────

const props = defineProps<{
  /** Tab identifier — used to look up tab config in tabsStore. */
  terminalId: string
}>()

// ── Stores ───────────────────────────────────────────────────────────────────

const tabsStore = useTabsStore()
const tasksStore = useTasksStore()

// ── State ────────────────────────────────────────────────────────────────────

const events = ref<StreamEvent[]>([])
const inputText = ref('')
const scrollContainer = ref<HTMLElement | null>(null)
const sessionId = ref<string | null>(null)
/** Agent process ID returned by agentCreate — used for IPC send and kill. */
const ptyId = ref<string | null>(null)

/** Collapsible state keyed by "eventIndex-blockIndex". */
const collapsed = ref<Record<string, boolean>>({})

/**
 * True once the user has clicked "Stop" (T683).
 * Used to hide the Stop button immediately after click and prevent double-kill.
 * Reset to false on each new message send so the button re-appears if agent restarts.
 */
const agentStopped = ref(false)

// ── Computed ─────────────────────────────────────────────────────────────────

/**
 * True while the last event is an assistant message (not yet followed by a result).
 * The result event marks the end of a turn.
 */
const isStreaming = computed(() => {
  if (events.value.length === 0) return false
  const last = events.value[events.value.length - 1]
  return last.type === 'assistant'
})

// ── Agent color theme (T680) ──────────────────────────────────────────────────

/** Agent name from active tab — drives the color theme. */
const agentName = computed(() => {
  const tab = tabsStore.tabs.find(t => t.id === props.terminalId)
  return tab?.agentName ?? ''
})

/** Reactive foreground accent color for the current agent. */
const accentFg = computed(() => {
  void colorVersion.value
  return agentName.value ? agentFg(agentName.value) : 'hsl(270, 60%, 68%)'
})

/** Reactive background accent color for the current agent. */
const accentBg = computed(() => {
  void colorVersion.value
  return agentName.value ? agentBg(agentName.value) : 'hsl(270, 30%, 18%)'
})

/** Reactive border accent color for the current agent. */
const accentBorder = computed(() => {
  void colorVersion.value
  return agentName.value ? agentBorder(agentName.value) : 'hsl(270, 30%, 32%)'
})

/**
 * Events filtered for display — suppresses empty user bubbles generated by
 * autonomous Claude reasoning (T679). A user event is hidden when all its text
 * blocks are empty or whitespace-only.
 */
const displayEvents = computed(() =>
  events.value.filter(event => {
    if (event.type !== 'user') return true
    if (!event.message) return false
    const textContent = event.message.content
      .filter(b => b.type === 'text')
      .map(b => b.text ?? '')
      .join('')
    return textContent.trim().length > 0
  })
)

// ── IPC ──────────────────────────────────────────────────────────────────────

let unsubStreamMessage: (() => void) | null = null
let unsubConvId: (() => void) | null = null
let unsubExit: (() => void) | null = null

async function sendMessage(): Promise<void> {
  const text = inputText.value.trim()
  if (!text || !sessionId.value) return
  const msgText = text
  inputText.value = ''
  // Reset so the Stop button re-appears on the new agent response (T683).
  agentStopped.value = false
  // Optimistic UI: display user bubble immediately
  events.value.push({
    type: 'user',
    message: { role: 'user', content: [{ type: 'text', text: msgText }] }
  })
  scrollToBottom()

  // ADR-009: agentSend writes a JSONL message to the agent's stdin — no respawn needed.
  try {
    if (ptyId.value) {
      await window.electronAPI.agentSend(ptyId.value, msgText)
    }
  } catch (err) {
    events.value.push({ type: 'system', subtype: 'error', session_id: `Erreur agent: ${String(err)}` })
  }
}

function handleKeydown(e: KeyboardEvent): void {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    sendMessage()
  }
}

/**
 * Kills the agent process immediately (T683).
 * Sets agentStopped to hide the button and prevent double-kill.
 * isStreaming stays true until an event 'result' arrives — onAgentExit resets it
 * by pushing a synthetic result event.
 */
function stopAgent(): void {
  if (!ptyId.value || agentStopped.value) return
  agentStopped.value = true
  window.electronAPI.agentKill(ptyId.value)
}

function toggleCollapsed(key: string): void {
  collapsed.value[key] = !collapsed.value[key]
}

function collapseKey(eventIdx: number, blockIdx: number): string {
  return `${eventIdx}-${blockIdx}`
}

function isCollapsed(eventIdx: number, blockIdx: number): boolean {
  const key = collapseKey(eventIdx, blockIdx)
  // thinking blocks are collapsed by default
  return collapsed.value[key] ?? false
}

// ── Micro-batching (T676) ──────────────────────────────────────────────────
// Accumulate incoming IPC events in a non-reactive buffer, then flush once per
// nextTick — avoids 1 re-render per JSONL line at high-frequency streaming.

let pendingEvents: StreamEvent[] = []
let flushPending = false

function flushEvents(): void {
  if (pendingEvents.length === 0) { flushPending = false; return }
  for (const e of pendingEvents) events.value.push(e)
  pendingEvents = []
  flushPending = false
  scrollToBottom()
}

function scrollToBottom(): void {
  nextTick(() => {
    if (scrollContainer.value) {
      scrollContainer.value.scrollTop = scrollContainer.value.scrollHeight
    }
  })
}

// ── Lifecycle ─────────────────────────────────────────────────────────────────

/**
 * Lifecycle: spawns the agent process, registers all IPC subscriptions,
 * then sends the initial message if autoSend is set (T689 race condition fix).
 *
 * Subscription order is critical: onAgentStream, onAgentConvId, and onAgentExit
 * are registered BEFORE agentSend is called so that no JSONL events are lost
 * if Claude responds faster than the subscription round-trip (T689).
 *
 * For resumed sessions (convId present, no autoSend), sessionId is set
 * immediately from the known convId so the Send button is enabled without
 * waiting for the system:init IPC event (ADR-009).
 */
onMounted(async () => {
  const tab = tabsStore.tabs.find(t => t.id === props.terminalId)
  if (!tab) return

  // Resume shortcut: set sessionId immediately from known convId so the "Envoyer" button
  // is enabled right away. agentCreate still spawns the process — this avoids the button
  // being disabled while waiting for system:init from a resumed session (ADR-009).
  if (tab.convId && !tab.autoSend) {
    sessionId.value = tab.convId
  }

  try {
    // ADR-009: spawn agent via child_process.spawn + stdio:pipe (no PTY, no ANSI).
    const id = await window.electronAPI.agentCreate({
      projectPath: tasksStore.projectPath ?? undefined,
      wslDistro: tab.wslDistro ?? undefined,
      systemPrompt: tab.systemPrompt ?? undefined,
      thinkingMode: tab.thinkingMode ?? undefined,
      claudeCommand: tab.claudeCommand ?? undefined,
      convId: tab.convId ?? undefined,
    })
    ptyId.value = id
    tabsStore.setPtyId(props.terminalId, id)

    // Subscribe to JSONL stream events BEFORE sending — avoids race condition where
    // Claude responds before onAgentStream is registered and events are lost (T689).
    // Events are micro-batched: buffered in pendingEvents[], flushed once per nextTick (T676).
    unsubStreamMessage = window.electronAPI.onAgentStream(
      id,
      (raw: Record<string, unknown>) => {
        pendingEvents.push(raw as StreamEvent)
        if (!flushPending) {
          flushPending = true
          nextTick(flushEvents)
        }
      }
    )

    // Subscribe to convId channel — fired by main process on system:init
    unsubConvId = window.electronAPI.onAgentConvId(id, (convId: string) => {
      sessionId.value = convId
    })

    // Subscribe to exit — push a synthetic result event so isStreaming resets to false.
    // Needed when the agent is killed via stopAgent() which produces no 'result' JSONL line.
    unsubExit = window.electronAPI.onAgentExit(id, (_exitCode: number | null) => {
      if (isStreaming.value) {
        events.value.push({ type: 'result' })
      }
    })

    // Push user bubble immediately, then send via stdin JSONL (no respawn needed).
    // agentSend is called AFTER all subscriptions are registered (T689 race condition fix).
    if (tab.autoSend) {
      events.value.push({
        type: 'user',
        message: { role: 'user', content: [{ type: 'text', text: tab.autoSend }] }
      })
      scrollToBottom()
      await window.electronAPI.agentSend(id, tab.autoSend)
    }
  } catch (err) {
    events.value.push({ type: 'system', subtype: 'init', session_id: `Erreur agent: ${String(err)}` })
  }
})

onUnmounted(() => {
  unsubStreamMessage?.()
  unsubConvId?.()
  unsubExit?.()
  // Skip kill if already stopped via the Stop button (agentKill is idempotent but avoids noise).
  if (ptyId.value && !agentStopped.value) {
    window.electronAPI.agentKill(ptyId.value)
  }
})

// ── Helpers ───────────────────────────────────────────────────────────────────

function toolInputPreview(input: Record<string, unknown> | undefined): string {
  if (!input) return ''
  try {
    return JSON.stringify(input, null, 2)
  } catch {
    return String(input)
  }
}

function toolResultText(content: StreamContentBlock['content']): string {
  if (!content) return ''
  if (typeof content === 'string') return content
  if (Array.isArray(content)) {
    return content.map(c => c.text ?? '').join('\n')
  }
  return String(content)
}
</script>

<template>
  <div class="flex flex-col h-full bg-zinc-950 text-zinc-100 font-mono text-sm">
    <!-- ── Agent color accent header bar (T680) ──────────────────────────── -->
    <div
      v-if="agentName"
      class="h-0.5 w-full shrink-0"
      :style="{ background: accentFg }"
    />

    <!-- ── Messages scroll area ─────────────────────────────────────────── -->
    <div
      ref="scrollContainer"
      class="flex-1 overflow-y-auto px-4 py-4 space-y-3"
    >
      <!-- No messages placeholder -->
      <div
        v-if="displayEvents.length === 0 && !isStreaming"
        class="flex items-center justify-center h-full text-zinc-500 text-xs"
        data-testid="empty-state"
      >
        En attente de messages…
      </div>

      <template
        v-for="(event, eIdx) in displayEvents"
        :key="eIdx"
      >
        <!-- system:init -->
        <div
          v-if="event.type === 'system' && event.subtype === 'init'"
          class="text-zinc-500 text-xs italic"
          data-testid="block-system-init"
        >
          Session démarrée
          <span
            v-if="event.session_id"
            class="ml-1 font-mono"
          >· {{ event.session_id.slice(0, 8) }}…</span>
        </div>

        <!-- user message — bulle utilisateur alignée à droite -->
        <div
          v-if="event.type === 'user' && event.message"
          class="flex justify-end"
          data-testid="block-user"
        >
          <div
            class="bg-zinc-800 border rounded-lg px-4 py-3 max-w-[80%] whitespace-pre-wrap text-sm text-zinc-100 leading-relaxed"
            :style="{ borderColor: accentBorder }"
          >
            <template v-for="(block, bIdx) in event.message.content" :key="bIdx">
              <span v-if="block.type === 'text'">{{ block.text }}</span>
            </template>
          </div>
        </div>

        <!-- assistant message blocks -->
        <template v-if="event.type === 'assistant' && event.message">
          <template
            v-for="(block, bIdx) in event.message.content"
            :key="`${eIdx}-${bIdx}`"
          >
            <!-- text block — rendu Markdown DOMPurify (T678), border-left couleur agent (T680) -->
            <div
              v-if="block.type === 'text'"
              class="stream-markdown bg-zinc-800 rounded-lg px-4 py-3 border border-zinc-700 border-l-2 leading-relaxed"
              :style="{ borderLeftColor: accentFg }"
              data-testid="block-text"
              v-html="renderMarkdown(block.text ?? '')"
            />

            <!-- thinking block — collapsible grisé -->
            <div
              v-else-if="block.type === 'thinking'"
              class="border border-zinc-700 rounded-lg overflow-hidden"
              data-testid="block-thinking"
            >
              <button
                class="w-full flex items-center gap-2 px-3 py-2 bg-zinc-900 hover:bg-zinc-800 transition-colors text-zinc-400 text-xs"
                @click="toggleCollapsed(collapseKey(eIdx, bIdx))"
              >
                <span class="transition-transform duration-200" :class="isCollapsed(eIdx, bIdx) ? '' : 'rotate-90'">▶</span>
                <span>Thinking…</span>
              </button>
              <div
                v-show="!isCollapsed(eIdx, bIdx)"
                class="px-4 py-3 bg-zinc-900 text-zinc-400 text-xs whitespace-pre-wrap"
              >
                {{ block.text }}
              </div>
            </div>

            <!-- tool_use block — carte collapsible couleur agent (T680) -->
            <div
              v-else-if="block.type === 'tool_use'"
              class="border rounded-lg overflow-hidden"
              :style="{ borderColor: accentBorder }"
              data-testid="block-tool-use"
            >
              <button
                class="w-full flex items-center gap-2 px-3 py-2 transition-colors text-xs"
                :style="{ backgroundColor: accentBg, color: accentFg }"
                @click="toggleCollapsed(collapseKey(eIdx, bIdx))"
              >
                <span class="transition-transform duration-200" :class="isCollapsed(eIdx, bIdx) ? '' : 'rotate-90'">▶</span>
                <span class="font-semibold">{{ block.name }}</span>
                <span class="ml-auto opacity-60">outil</span>
              </button>
              <div
                v-show="!isCollapsed(eIdx, bIdx)"
                class="px-4 py-3 bg-zinc-900 text-xs text-zinc-300 overflow-x-auto"
              >
                <pre class="whitespace-pre-wrap">{{ toolInputPreview(block.input) }}</pre>
              </div>
            </div>

            <!-- tool_result block — sortie code -->
            <div
              v-else-if="block.type === 'tool_result'"
              class="border rounded-lg overflow-hidden"
              :class="block.is_error ? 'border-red-800 bg-red-950' : 'border-zinc-700 bg-zinc-900'"
              data-testid="block-tool-result"
            >
              <div class="px-3 py-1.5 text-xs flex items-center gap-2"
                :class="block.is_error ? 'text-red-400' : 'text-zinc-400'"
              >
                <span>{{ block.is_error ? '✗ Erreur' : '✓ Résultat' }}</span>
              </div>
              <pre
                class="px-4 py-2 text-xs text-zinc-300 overflow-x-auto whitespace-pre-wrap"
              >{{ toolResultText(block.content) }}</pre>
            </div>
          </template>
        </template>

        <!-- result footer — coût / durée / tokens -->
        <div
          v-if="event.type === 'result'"
          class="flex flex-wrap gap-4 text-xs text-zinc-500 border-t border-zinc-800 pt-2"
          data-testid="block-result"
        >
          <span v-if="event.num_turns !== undefined">
            {{ event.num_turns }} tour{{ event.num_turns > 1 ? 's' : '' }}
          </span>
          <span v-if="event.cost_usd !== undefined">
            ${{ event.cost_usd.toFixed(4) }}
          </span>
          <span v-if="event.duration_ms !== undefined">
            {{ (event.duration_ms / 1000).toFixed(1) }}s
          </span>
          <span
            v-if="event.session_id"
            class="ml-auto font-mono text-zinc-600"
          >
            {{ event.session_id.slice(0, 8) }}…
          </span>
        </div>
      </template>

      <!-- Indicateur "en cours" — couleur agent (T680) -->
      <div
        v-if="isStreaming"
        class="flex items-center gap-2 text-xs"
        :style="{ color: accentFg }"
        data-testid="streaming-indicator"
      >
        <span class="inline-flex gap-0.5">
          <span class="w-1.5 h-1.5 rounded-full animate-bounce [animation-delay:0ms]" :style="{ backgroundColor: accentFg }" />
          <span class="w-1.5 h-1.5 rounded-full animate-bounce [animation-delay:150ms]" :style="{ backgroundColor: accentFg }" />
          <span class="w-1.5 h-1.5 rounded-full animate-bounce [animation-delay:300ms]" :style="{ backgroundColor: accentFg }" />
        </span>
        <span>En cours…</span>
      </div>
    </div>

    <!-- ── Input zone (T681: items-end aligne boutons sur bas textarea) ─── -->
    <div class="border-t border-zinc-800 px-4 py-3 flex items-end gap-2">
      <textarea
        v-model="inputText"
        rows="2"
        placeholder="Envoyer un message…"
        class="flex-1 resize-none bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:ring-1 transition-colors"
        @keydown="handleKeydown"
      />
      <!-- Stop button (T683) — visible only while agent is streaming and not yet stopped -->
      <button
        v-if="isStreaming && ptyId && !agentStopped"
        class="px-4 py-2 bg-red-700 hover:bg-red-600 text-white rounded-lg text-sm font-medium transition-colors self-end"
        data-testid="stop-button"
        @click="stopAgent"
      >
        Stop
      </button>
      <!-- Send button — couleur agent quand actif, zinc-700 quand disabled (T680) -->
      <button
        :disabled="!inputText.trim() || !sessionId"
        class="px-4 py-2 disabled:bg-zinc-700 disabled:text-zinc-500 text-white rounded-lg text-sm font-medium transition-colors self-end"
        :style="inputText.trim() && sessionId ? { backgroundColor: accentFg } : {}"
        data-testid="send-button"
        @click="sendMessage"
      >
        Envoyer
      </button>
    </div>
  </div>
</template>

<style>
/* Markdown prose styles for assistant text blocks (T678).
   Scoped to .stream-markdown to avoid polluting other components.
   No scoped attribute — these classes are injected via v-html so Vue scoped won't match. */
.stream-markdown {
  line-height: 1.65;
}
.stream-markdown p { margin: 0.5em 0; }
.stream-markdown p:first-child { margin-top: 0; }
.stream-markdown p:last-child { margin-bottom: 0; }
.stream-markdown h1,
.stream-markdown h2,
.stream-markdown h3,
.stream-markdown h4 {
  font-weight: 600;
  margin: 0.85em 0 0.35em;
  color: #f4f4f5;
}
.stream-markdown h1 { font-size: 1.25em; }
.stream-markdown h2 { font-size: 1.1em; }
.stream-markdown h3 { font-size: 1em; }
.stream-markdown ul,
.stream-markdown ol { padding-left: 1.4em; margin: 0.4em 0; }
.stream-markdown li { margin: 0.2em 0; }
.stream-markdown code:not(pre code) {
  background: rgba(255, 255, 255, 0.08);
  border-radius: 3px;
  padding: 0.1em 0.35em;
  font-size: 0.85em;
  color: #e4e4e7;
}
.stream-markdown pre { margin: 0.6em 0; border-radius: 6px; overflow-x: auto; }
.stream-markdown pre code { font-size: 0.8em; padding: 0.85em 1em; display: block; }
.stream-markdown blockquote {
  border-left: 3px solid rgba(255, 255, 255, 0.2);
  padding-left: 0.8em;
  margin: 0.4em 0;
  color: #a1a1aa;
}
.stream-markdown a { color: #818cf8; text-decoration: underline; }
.stream-markdown strong { font-weight: 600; }
.stream-markdown em { font-style: italic; }
.stream-markdown hr { border: none; border-top: 1px solid rgba(255, 255, 255, 0.1); margin: 0.8em 0; }
</style>
